export const metadata = {
	title: 'GameDev Tavern | Авторизация',
	description: 'Generated by Next.js'
}

export default function AuthLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<main className='flex flex-col justify-center pt-40'>
			<div className='bg-custom-white mx-4 flex justify-between rounded-2xl sm:mx-auto'>
				{children}
			</div>
		</main>
	)
}
